version: '2'
services:
  database:
    container_name: datagraft-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: whatever
      POSTGRES_DB: datagraft-prod
  portal:
    container_name: datagraft-rails
    image: yellowiscool/datagraftreturn
    ports:
      - "3003:3000"
    links:
      - database:postgres
    environment:
      DATABASE_URL: postgresql://postgres:whatever@postgres
      RAILS_ENV: production
      SECRET_KEY_BASE: 750184ddf9d54ca16fee171034f7e4fd7df4b8398efa30c6d36966b24f1d3460209566919a6cf05415017f2b8af7dd65e9b17e423ab95ec783773d8d36421281
      OMNIAUTH_FACEBOOK_KEY: facebookkey
      OMNIAUTH_FACEBOOK_SECRET: facebooksecret
      OMNIAUTH_GITHUB_KEY: githubkey
      OMNIAUTH_GITHUB_SECRET: githubsecret
  grafterizer-web:
    container_name: grafterizer-web
    image: dapaas/grafterizer-web-dev
    ports:
      - "8081:80"
    links:
      - graftwerk
      - backend
      - vocabulary
      - graftwerkcache
      - jarfter
    restart: always
  backend:
    container_name: grafterizer-backend-rest
    image: dapaas/grafterizer-rest-dev
    links:
      - graftwerk
      - graftwerkcache
      - portal
    ports:
      - "8082:8082"
    environment:
      COOKIE_STORE_SECRET: 8a84916a5e72de9de416c7ba4fffc9ad73b9b615d6114cbd44d1974ff040e885a5b88c480eb1c1b409e364dd65003efe2c0ff70a4fd0aece0eaacffb32f2cc89
      OAUTH2_CLIENT_ID: 49ef5d705ed7c76f7529fe358bdc981e82ad681cae75a8c70061d7f98e47660b
      OAUTH2_CLIENT_SECRET: 4f976fd05a042cf82cb8b48f18ee3faa130dfb4202029fd22606dc2db868b805
      GRAFTWERK_URI: http://graftwerk:8080
      GRAFTWERK_CACHE_URI: http://graftwerkcache:8082
      DATAGRAFT_URI: http://portal:3000
      # Public URI of grafterizer-web-dev.
      # This URI MUST be accessible by the end-user.
      CORS_ORIGIN: http://localhost:8081
      # Public URI of the backend server.
      # This URI MUST be accessible by the end-user.
      PUBLIC_CALLBACK_SERVER: http://localhost:8082
      # same as DATAGRAFT_URI by default
      # OAUTH2_SITE: http://portal:3000
      PUBLIC_OAUTH2_SITE: http://localhost:3003
    restart: always
  graftwerkcache:
    container_name: grafterizer-cache
    image: dapaas/grafter-memcache:cors
    ports:
      - "8083:8082"
    links:
      - graftwerk
    environment:
      GRAFTWERK: graftwerk
      GRAFTWERK_PORT: 8080
    restart: always
  graftwerk:
    container_name: graftwerk
    image: dapaas/graftwerk
    restart: always
  vocabulary:
    container_name: grafterizer-vocab
    image: dapaas/grafterizer-vocabulary:latest
    restart: always
  jarfter:
    container_name: jarfter
    image: dapaas/jarfter:latest
    restart: always

